[log]
disable-timestamp = false
level = "info"
format = "text"
filename = "/tmp/robber-repository/data.log"
maxsize = 20

[mysql]
dsn = "root:root@tcp(localhost:3306)/robber?charset=utf8mb4&parseTime=true&loc=Local"
min-open = 5
max-open = 10

[etcd]
endpoints = [
	"localhost:2379",
]

[server]
host = "0.0.0.0"
port = 19092
