[log]
disable-timestamp = false
level = "info"
format = "text"
filename = "/var/log/robber-repository/data.log"
maxsize = 20

[mysql]
dsn = "root:root@tcp(172.17.0.1:3306)/robber?charset=utf8mb4&parseTime=true&loc=Local"
min-open = 5
max-open = 10

[etcd]
endpoints = [
	"172.17.0.1:2379",
]

[server]
host = "0.0.0.0"
port = 19092
