// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.1.0
// - protoc             v3.19.1
// source: repository.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.StringValue, error)
	PushData(ctx context.Context, opts ...grpc.CallOption) (Service_PushDataClient, error)
	GetStockFull(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Service_GetStockFullClient, error)
	GetQuoteLatest(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (Service_GetQuoteLatestClient, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.StringValue, error) {
	out := new(wrapperspb.StringValue)
	err := c.cc.Invoke(ctx, "/repository.Service/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) PushData(ctx context.Context, opts ...grpc.CallOption) (Service_PushDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &Service_ServiceDesc.Streams[0], "/repository.Service/PushData", opts...)
	if err != nil {
		return nil, err
	}
	x := &servicePushDataClient{stream}
	return x, nil
}

type Service_PushDataClient interface {
	Send(*Metadata) error
	CloseAndRecv() (*emptypb.Empty, error)
	grpc.ClientStream
}

type servicePushDataClient struct {
	grpc.ClientStream
}

func (x *servicePushDataClient) Send(m *Metadata) error {
	return x.ClientStream.SendMsg(m)
}

func (x *servicePushDataClient) CloseAndRecv() (*emptypb.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(emptypb.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serviceClient) GetStockFull(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Service_GetStockFullClient, error) {
	stream, err := c.cc.NewStream(ctx, &Service_ServiceDesc.Streams[1], "/repository.Service/GetStockFull", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceGetStockFullClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Service_GetStockFullClient interface {
	Recv() (*Stock, error)
	grpc.ClientStream
}

type serviceGetStockFullClient struct {
	grpc.ClientStream
}

func (x *serviceGetStockFullClient) Recv() (*Stock, error) {
	m := new(Stock)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serviceClient) GetQuoteLatest(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (Service_GetQuoteLatestClient, error) {
	stream, err := c.cc.NewStream(ctx, &Service_ServiceDesc.Streams[2], "/repository.Service/GetQuoteLatest", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceGetQuoteLatestClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Service_GetQuoteLatestClient interface {
	Recv() (*Quote, error)
	grpc.ClientStream
}

type serviceGetQuoteLatestClient struct {
	grpc.ClientStream
}

func (x *serviceGetQuoteLatestClient) Recv() (*Quote, error) {
	m := new(Quote)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	Version(context.Context, *emptypb.Empty) (*wrapperspb.StringValue, error)
	PushData(Service_PushDataServer) error
	GetStockFull(*emptypb.Empty, Service_GetStockFullServer) error
	GetQuoteLatest(*QuoteRequest, Service_GetQuoteLatestServer) error
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) Version(context.Context, *emptypb.Empty) (*wrapperspb.StringValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedServiceServer) PushData(Service_PushDataServer) error {
	return status.Errorf(codes.Unimplemented, "method PushData not implemented")
}
func (UnimplementedServiceServer) GetStockFull(*emptypb.Empty, Service_GetStockFullServer) error {
	return status.Errorf(codes.Unimplemented, "method GetStockFull not implemented")
}
func (UnimplementedServiceServer) GetQuoteLatest(*QuoteRequest, Service_GetQuoteLatestServer) error {
	return status.Errorf(codes.Unimplemented, "method GetQuoteLatest not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/repository.Service/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Version(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_PushData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServiceServer).PushData(&servicePushDataServer{stream})
}

type Service_PushDataServer interface {
	SendAndClose(*emptypb.Empty) error
	Recv() (*Metadata, error)
	grpc.ServerStream
}

type servicePushDataServer struct {
	grpc.ServerStream
}

func (x *servicePushDataServer) SendAndClose(m *emptypb.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *servicePushDataServer) Recv() (*Metadata, error) {
	m := new(Metadata)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Service_GetStockFull_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceServer).GetStockFull(m, &serviceGetStockFullServer{stream})
}

type Service_GetStockFullServer interface {
	Send(*Stock) error
	grpc.ServerStream
}

type serviceGetStockFullServer struct {
	grpc.ServerStream
}

func (x *serviceGetStockFullServer) Send(m *Stock) error {
	return x.ServerStream.SendMsg(m)
}

func _Service_GetQuoteLatest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QuoteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceServer).GetQuoteLatest(m, &serviceGetQuoteLatestServer{stream})
}

type Service_GetQuoteLatestServer interface {
	Send(*Quote) error
	grpc.ServerStream
}

type serviceGetQuoteLatestServer struct {
	grpc.ServerStream
}

func (x *serviceGetQuoteLatestServer) Send(m *Quote) error {
	return x.ServerStream.SendMsg(m)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "repository.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Service_Version_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushData",
			Handler:       _Service_PushData_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetStockFull",
			Handler:       _Service_GetStockFull_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetQuoteLatest",
			Handler:       _Service_GetQuoteLatest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "repository.proto",
}
